# Generated by Django 4.2.13 on 2024-07-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='created_by',
        ),
    ]
